### ISSUE TITLE
remove confusion

### ISSUE THREAD

**Issue by rubydesign** [TheArtificial/rails-wiki#12]
Hi,

somehow got a mail about this and read the README. Being the maintainer of GollumRails i would like to suggest you remove the "GollumRails, which confusingly does not use gollum-lib", which is much vaguer than need be. 

The reasons are now historic: at the time gollum-lib was a moving undocumented target. I inherited the project when the gollum expert left and it was easier to use the git wrapper without the lib. Maybe you can use "for historical reasons"

On a higher level: I do not use the GollumnRails as my project went south. Initially i only offered to help, but then got the whole thing, without really wanting it. And so it may be worth considering for you to adopt the name: Since you seem to use gollum-lib and maintain this, you could just take over the GollumnRails name (gem and all), but use your code . It would be easier for people for find and make the association. Then they might even let you back in the gollum organization.

**Comment by gerwitz** [comment]
You probably received mail because of issue #9, which I never followed up on because this side project only gets attention when something breaks. ;-)

Thanks for the "brand inheriting" offer … I may take you up on it someday if I ever finish #3 and decide to stay with gollum-lib. Considering how little of it we're using, that's not quite a given.

**Comment by rubydesign** [comment]
Right, i new this sounded familiar, now i remember.

I certainly understand about the not using the lib, which is what got me off it. I implemented what i needed in 12 hours. 

I'll close this as it's a duplicate. The offer stands though
